### ISSUE TITLE
Provide location as output

### ISSUE THREAD

**Issue by Vampire** [pbrisbin/setup-tool-action#76]
I use (or try to) your action to download an exe file on a Linux or macOS runner that I then feed to `wine` for installation.

Can you please provide the path to the downloaded file and / or extracted directory as output of the action?

Just having it in the `PATH` is not sufficient for this use-case.

**Comment by pbrisbin** [comment]
I've added the `directory` output in #79. I don't think I can add an output for the executable(s), since we don't know what they'll extract. Hopefully `directory` is enough. You can test this now by using `pbrisbin/setup-action-tool@pb/next`, but I should be releasing the next version soon.

**Comment by Vampire** [comment]
I do not understand actually, because again, there is no extracting happening in my case. :-)

**Comment by pbrisbin** [comment]
Hmm,

> ```yaml
> url: 'https://files.jrsoftware.org/is/6/innosetup-{version}.exe'
> ```
>
> ```yaml
> command: 'wine ${{ steps.provision-innosetup.outputs.directory }}/innosetup.exe ...'
> ```

How does `innosetup-{version}.exe` become `.../innosetup.exe` between these two examples?

**Comment by pbrisbin** [comment]
Ah, because it's downloaded to `name`. I see. So, if-and-only-if one uses `no-extract: true` then `outputs.directory/inputs.name` is what I could spit back as `file. I'm not sure it's worth it. :thinking:

**Comment by pbrisbin** [comment]
OK, I think simply echoing back `outputs.file = outputs.directory/inputs.name` would be valuable. If nothing else, we cna at least take care of the cross-platform `fs.join` needed. So I do plan to add it, but I decided to merge that other PR first since it fixes a bunch of things.
